### ISSUE TITLE
Flag Logs empty

### ISSUE THREAD

**Issue by RobCoding** [Charcoal-SE/metasmoke#561] opened 2019-01-10 22:13 UTC
On CHQ I mentioned to Makyen that the "Flag Logs" are empty, he confirms that this is a problem for him too.

Conversation from CHQ:

@Makyen When I go to "MS" and click on the 🏳️ it takes me to this webpage: https://metasmoke.erwaysoftware.com/post/153411/flag_logs for the Logs, but there are always no entries; even if I'm a flagger. 

@Rob Yeah, that link has never worked for me either. I've assumed it's a bug, because the data is available from the API.

Link to conversation on CHQ: https://chat.stackexchange.com/transcript/message/48447938#48447938

We are only able to click on *something* when there is a 'flag icon' (🏳️) it would be great to be able to click on the title too.

The main concern of this Bug Report is that occasionally a flag icon appears, but clicking on it takes us to a 'template' webpage which has room for entries (presumably our own flags and any others we have permission to see) but the webpage isn't populated with the information that we were expecting to see.

This is what I see:

"Flag logs for In CA, Old car registration/smog is Due, Can I sell the car?
User 	Post 	Result
Eligible Flaggers

We are Charcoal ...".

Clicking on the "Eligible Flaggers" link simply dismisses it, and no listing is provided.

Expected operation: Clicking on the title or IF the rare flag icon appears clicking on that should provide some historical information. 

When clicking on the flag icon and being presented with the "Eligible Flaggers" link clicking on it should do something instead of nothing.

**Comment by ArtOfCode-** [comment] 2019-01-10 22:17
If you see a _filled_ flag icon, the post had autoflags cast on it; clicking the icon will take you to that page, which will show you the autoflag records.

If you see an _empty_ flag icon, the post had manual or "other" flags cast on it; clicking the icon will still take you to that page, but it only shows autoflags - you'll see no logs.

Half-bug, half-FR.

**Comment by makyen** [comment] 2019-01-11 00:21
Sounds like this could be fixed in a few different ways: 

If there are manual flags and no autoflags:
1. The empty flag is not clickable.
2. The empty flag is not displayed.
3. The page linked by the empty flag shows the users that flagged. This information is available from the MS API, so is considered public.

If 3 is done, then it would be reasonable to display the manual flags in addition to the autoflags when both are present.

**Comment by ArtOfCode-** [comment] 2019-01-11 20:01
I think I originally intended to do 3, then deployed it before I managed and promptly forgot... [status-on-the-todo-list]

**Comment by makyen** [comment] 2019-01-11 21:50
Yeah, is not a really critical issue, but it does appear it's causing some confusion. When I was first looking at those pages I ended up comparing what was returned from the MS API for manual flags and what was displayed on that page. Doing so confirmed for me that the issue was just that the page didn't display manual flags, rather than that the record of manual flags had been lost/didn't exist.

IMO, this isn't a big issue, but clearly is causing some confusion. A stop-gap that would help reduce confusion would be to change what is displayed on the `/flag_logs` page from "Flag logs for" to "Autoflag logs for". That would make it clear that the listing is only intended to include autoflags and not manual flags. I've added that as option 4 in my list above.

**Closed** 2019-02-03 22:16 UTC
Labels: type: bug, type: feature request
