### ISSUE TITLE
Please revert the review count back from "50+"

### ISSUE THREAD

**Issue by Daniil-M-beep** [Charcoal-SE/metasmoke#800] opened 2020-08-26 23:20 UTC
Right now the review count shows "50+" but please make it display the actual review count.

> You just went off and made the change without leaving a way to see the actual review count (apart from the bug but that displays it but you were not aware of that so it should not be mentioned in this discussion). Then when I ask a way to see the count presuming the bug gets fixed soon you insult me by saying not to start an argument.

> That's not the point. When there is a group discussion you do not go and implement your solution without anyone else's opinion because you have access and others don't.

> Also I don't see why I should make an effort to change something back when it was never agreed on by anyone.

> The problem was not urgent enough for there to be an immediate solution implemented which was agreed to by no-one bar one person and wasn't a direct solution to the problem.

> It wasn't a complete solution or any solution at all actually and this could have been discussed. Just because a person has write access to make the change themselves doesn't mean they should follow a different procedure from a person who doesn't have access if it's not a serious problem.
You could have made an issue about this, made a PR or even just asked here before implementing it yourself.

> Well I care. So I don't see the reasons why the person who doesn't care makes a change because they have access (without the approval of anyone else) but the person who does care and who the change will make a effect on (even if small) has to go through the trouble of making an issue and has to somehow hope that someone finds time for it when it's proven by evidence that a lot of issues aren't paid attention to all because a person who don't care made a change because they have access.

> So I've got to go through the trouble of searching through the commits, reverting it and guessing if the code works (I don't know Ruby at all) just in case you find time, even though the change in question doesn't affect you, is not a solution to the problem discussed and was not agreed on by anyone apart from you. Correct?

I think that sums up the reasons very nicely.

**Comment by user12986714** [comment] 2020-08-27 00:15
I can see the argument to allow users to opt in to see actual review count, for transparency mainly. However, I do think it is beneficial to also allow users to opt to see '50+' as some may feel going through a queue with 25000 item is discouraging.

**Comment by Undo1** [comment] 2020-08-27 00:22
Anything wrong with just showing the true count in a tooltip?

**Comment by user12986714** [comment] 2020-08-27 01:01
Related issue #792 . Regardless what we decide on changing, the problem described in the linked issue should still be solved, as we are pretty sure that this is not the intended behaviour and something is wrong.

**Comment by Daniil-M-beep** [comment] 2020-08-27 08:25
> Anything wrong with just showing the true count in a tooltip?

No, no problem. As long as there is an easy way to see the actual count.

**Comment by user12986714** [comment] 2020-09-20 20:16
Once #822 is merged, this issue can be closed as the changes are reverted.

**Closed** 2020-09-20 20:43 UTC
Labels: area: ui, status: review, type: feedback wanted
