### ISSUE TITLE
Linking related domains is still erratic

### ISSUE THREAD

**Issue by tripleee** [Charcoal-SE/metasmoke#689] opened 2019-11-08 07:58 UTC
Creating a link always seems to create two identical links.

Just now, when I typed mailsdaddy.com into the domain name box, it was immediately emptied, and I ended up creating two links to "null domain".

This reproed several times, and the JavaScript pseudo-dialog appeared to get jammed at some point, though closing it and reloading the page fixed it.

MacOS Mojave, Chrome updated.

**Comment by ArtOfCode-** [comment] 2019-11-08 23:35
Duplicate of #459

**Closed by ArtOfCode-** 2019-11-08 23:35 UTC

**Comment by ArtOfCode-** [comment] 2019-11-08 23:37
This still hasn't been looked at - nobody's had the time to do it, particularly because it's low-priority and high-maintenance. It's still on my list, and I've just self-assigned the original issue about this, but it needs me to find a good block of time to spend looking at this one issue, which... is kinda rare these days. Until #459 is closed, you may consider domain links still broken, and I'd advise against using them in case things break.
