### ISSUE TITLE
"Multiple records were found for this URL; pick the one you meant from this list." stays on screen on other pages

### ISSUE THREAD

**Issue by ferrybig** [Charcoal-SE/metasmoke#155] opened 2017-04-08 12:12 UTC
1. Go to https://metasmoke.erwaysoftware.com/posts/by-url?url=//math.stackexchange.com/a/2223578
2. Click on your username in the right top
3. Go to "Feedback via api"
4. Observe that the "Multiple records were found for this URL; pick the one you meant from this list." banner is still present on that page

[![Banner still present][1]][1]

[1]: https://i.stack.imgur.com/Jb5Qk.png

**Comment by Fortunate-MAN** [comment] 2017-04-08 15:22
Reproduced on Chrome 57.0.2987.133 on OS X Sierra.

**Comment by angussidney** [comment] 2017-04-09 00:18
I think (?) this could be fixed by changing [this line](https://github.com/Charcoal-SE/metasmoke/blob/master/app/controllers/posts_controller.rb#L36) to use `flash.now`. Not entirely sure though.

**Closed** 2017-04-09 01:25 UTC

**Comment by angussidney** [comment] 2017-04-09 03:09
Seems to work

**Comment by Fortunate-MAN** [comment] 2017-04-09 03:59
Works for me too.
