### ISSUE TITLE
"Post deleted" on posts which aren't

### ISSUE THREAD

**Issue by tripleee** [Charcoal-SE/metasmoke#568] opened 2019-02-01 14:56 UTC
As reported by Rob:

https://chat.stackexchange.com/transcript/11540?m=48812470#48812470

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by RobCoding** [comment] 2019-02-01 15:23
The [2nd discussion that lead to the creation of this report](https://chat.stackexchange.com/transcript/message/48813111#48813111) has this reply from me, explaining the problem further:

> tripleee That's OK. If we can accumulate a few examples we can post them there. It's a problem because you think that the post is deleted, so there's no purpose clicking the link unless you are 10K (2K on some sites), but the post is there and never has been deleted; we are simply offering extraneous false information. Thanks for the brief bug report, it's sufficient.

**Comment by iBug** [comment] 2019-02-02 04:13
This is in fact a duplicate of Charcoal-SE/SmokeDetector#2172

**Comment by RobCoding** [comment] 2019-02-02 04:45
@iBug I agree. After checking with @Tripleee could we move these comments there, or post a comment there referencing this bug report, as this contains more info than @Glorfindel83 wrote.

**Closed** 2019-02-02 05:01 UTC

**Comment by Undo1** [comment] 2019-02-02 05:39
fixed, will not backport.
