### ISSUE TITLE
New auto-community-wiki answer is considered 'edited' and therefore not autoflagged

### ISSUE THREAD

**Issue by Glorfindel83** [Charcoal-SE/metasmoke#696] opened 2019-12-05 15:08 UTC
Case in point: https://metasmoke.erwaysoftware.com/post/212782
It'll probably be gone soon, but I saved the revision history:
https://web.archive.org/web/20191205150649/https://serverfault.com/posts/994471/revisions
You can see that FIRE thinks it has been edited as well: https://chat.stackexchange.com/transcript/message/52803982

**Comment by makyen** [comment] 2019-12-05 16:35
This is a duplicate of issue #574.

**Closed by makyen** 2019-12-05 16:35 UTC
Labels: area: flagging, type: bug, type: duplicate

**Comment by makyen** [comment] 2019-12-06 04:48
The above mentioned PR has been merged and MS has been deployed. At this point, this should be resolved.
