### ISSUE TITLE
Search: regex doesn't support character classes (e.g. \s, \b, \W, etc.)

### ISSUE THREAD

**Issue by makyen** [Charcoal-SE/metasmoke#351] opened 2018-03-17 17:58 UTC
When entering a regex into the [search page](https://metasmoke.erwaysoftware.com/search), I expected to be able to use character classes (e.g. `\s`, `\b`, `\W`, etc.). However, when I tried, the results were identical to searching a non-regex with the `\` character stripped.

Example:

| non-regex        | regex  |  |
| ------------- |-------------|-----|
| [Search for `sales`](https://metasmoke.erwaysoftware.com/search?utf8=%E2%9C%93&title=&body=sales&username=&why=&site=&post_type=&feedback=&autoflagged=&reason=&user_rep_direction=%3E%3D&user_reputation=0&commit=Search) | [Search for regex `sale\s`](https://metasmoke.erwaysoftware.com/search?utf8=%E2%9C%93&title=&body_is_regex=1&body=sale%5Cs&username=&why=&site=&post_type=&feedback=&autoflagged=&reason=&user_rep_direction=%3E%3D&user_reputation=0&commit=Search) | Results are, erroneously, identical |
| [Search for `saleb`](https://metasmoke.erwaysoftware.com/search?utf8=%E2%9C%93&title=&body=saleb&username=&why=&site=&post_type=&feedback=&autoflagged=&reason=&user_rep_direction=%3E%3D&user_reputation=0&commit=Search) | [Search for regex `sale\b`](https://metasmoke.erwaysoftware.com/search?utf8=%E2%9C%93&title=&body_is_regex=1&body=sale%5Cb&username=&why=&site=&post_type=&feedback=&autoflagged=&reason=&user_rep_direction=%3E%3D&user_reputation=0&commit=Search) | Results are, erroneously, identical |

**Comment by ArtOfCode-** [comment] 2018-03-25 22:31
Duplicate of #258

**Closed by ArtOfCode-** 2018-03-25 22:31 UTC
