### ISSUE TITLE
Can still see exact review count

### ISSUE THREAD

**Issue by user12986714** [Charcoal-SE/metasmoke#792] opened 2020-08-18 00:19 UTC
![image](https://user-images.githubusercontent.com/65436504/90456357-d29ef280-e0c6-11ea-8b11-461e289e7d35.png)

It appears that one can see actual review count (instead of '50+') after submitting a feedback on a post, if and only if the post originally has no feedback.

**Comment by user12986714** [comment] 2020-08-18 00:20
Step to reproduction: select a post with no feedback. Submit a feedback by clicking on either of the button. Now '50+' suddenly becomes the actual number (in this case 24590)

**Comment by thesecretmaster** [comment] 2020-08-27 14:40
Closing as a duplicate of #800, since that will address the same problem.

**Closed by thesecretmaster** 2020-08-27 14:40 UTC
Labels: type: bug

**Comment by user12986714** [comment] 2020-08-27 15:24
While I have no problem with this issue being closed, I still consider the displayed behaviour a bug, as going through the code base I found no reason for it to behave as such. This is likely a bug in Rails.
