### ISSUE TITLE
Broken formatting in chat link

### ISSUE THREAD

**Issue by tripleee** [Charcoal-SE/metasmoke#944] opened 2022-08-22 07:11 UTC
My comment on https://metasmoke.erwaysoftware.com/post/383440 is oddly mixing HTML and Markdown formatting, where the latter is displayed verbatim.

> Plagiarized from [ethereum.stackexchange.com/questions/134094/…](https://ethereum.stackexchange.com/questions/134094/error-hh8-theres-one-or-more-errors-in-your-config-file) with spam link added. Please flag accordingly. — [tripleee](https://ethereum.stackexchange.com/users/5061/tripleee) [27 secs ago](https‍://ethereum.stackexchange.com/questions/134097/theres-one-or-more-errors-in-your-config-file#comment154523_134097) – from a \[chat message](https‍://chat.stackexchange.com/transcript/message/61837565) by \[tripleee](https‍://chat.stackexchange.com/users/62118/tripleee)

Attempting to edit the message reveals that the working links are HTML and the non-working ones are Markdown.

**Comment by makyen** [comment] 2022-08-22 10:20
I managed to mis-click and delete the comment on MS, and *also* mess up the onebox in the source chat message of your deleted comment on Ethereum. I, unfortunately, didn't check to see if your original comment on Ethereum had been deleted prior to attempting to recreate the MS comment. I'm sorry about that. I've returned the chat message to a reasonable semblance of what it was, but using Markdown. I was attempting to re-create the MS comment which I'd accidentally deleted.

It's strange that it's not accepting Markdown in this, but does accept Markdown in other such comments. After my unfortunate misadventure attempting to return things to the way they were, it's clear that the issue is when forwarding a oneboxed message. A onebox is moderately complex HTML, which MS somewhat renders. However, it doesn't render the Markdown that was also there.

Having the new attribution in Markdown works under other circumstances. We can try changing the attribution to being in HTML, rather than Markdown to see if that works for both oneboxes and Markdown based chat replies.

**Comment by makyen** [comment] 2022-08-22 10:21
Another example of the issue for another forwarded onebox: https://metasmoke.erwaysoftware.com/post/383442

**Comment by makyen** [comment] 2022-08-22 12:01
I [updated the code](https://github.com/Charcoal-SE/SmokeDetector/commit/1f709a656ad9479fca9b81a5e523f96c0d7db333) to have the attribution in HTML instead of Markdown and did some testing [here](https://chat.stackexchange.com/transcript/message/61839355#61839355), which produced some comments on [this MS post](https://metasmoke.erwaysoftware.com/post/383491).

While the attribution is now displayed for a similar onebox of a chat comment, there was another issue which came up. [This chat message](https://chat.stackexchange.com/transcript/message/61839356#61839356) didn't result in an MS comment being posted.

**Comment by makyen** [comment] 2022-08-22 13:45
The new issue is that

    <div class="quote">This question is off-topic because it is not a practical programming problem. Thus, it's not within the scope of questions appropriate for this site, as defined in <a href="//stackoverflow.com/help/on-topic">What topics can I ask about here?</a> Please also see: <a href="//stackoverflow.com/help/dont-ask">What types of questions should I avoid asking?</a> You may be able to get help on <a href="//stackexchange.com/sites#name">another Stack Exchange site</a>. However, be sure to read the on-topic page for the site you select prior to posting. — <a rel="noopener noreferrer" href="https://stackoverflow.com/users/3773011/makyen">Makyen ♦</a> <a rel="noopener noreferrer" href="https://stackoverflow.com/questions/73158447/proper-vlan-isolation-for-exposed-server#comment129207586_73158447"><span title="2022-07-28 20:37:27Z" class="relativetime">Jul 28 at 20:37</span></a></div>

can't be added as a comment. It doesn't have anything to do with the new code. Trying to manually add that as a comment doesn't work either. The issue is that the `♦` causes the add to produce a `Mysql2::Error: Incorrect string value` error.

**Comment by teward** [comment] 2022-08-22 13:56
Is the DB on MS using utf-8 collation or an ascii collation?  UTF8 not being supported might be one of the string value errors causes.

**Comment by makyen** [comment] 2022-08-22 14:11
Yes, what range of characters are supported in that field is almost certainly the issue. We can do any of:
* Solve in SD
  * Strip unsupported characters, perhaps with some specific ones, like `♦`, converted into HTML entities
  * Convert all unsupported characters into HTML entities
* Solve in MS
  * Change the definition for that field in the database such that it accepts a wider range of characters.
  * Strip unsupported characters prior to adding the entry to, or updating the entry in, the database.
  * Convert unsupported characters to HTML entities.

We've had similar issues as this with other fields. In general, those have been resolved by changing the definition of the field in the database.

**Comment by makyen** [comment] 2022-08-22 15:14
I've [added a hack to SD](https://github.com/Charcoal-SE/SmokeDetector/commit/950a54e9aa2154a9bf7f61578446b28d3e107f50) to allow forwarding a oneboxed moderator comment into an MS comment by replying to a report in chat ([example in this post below the comment with `&diams;` in code format](https://metasmoke.erwaysoftware.com/post/383491)). We should still implement a general solution.

**Comment by makyen** [comment] 2022-08-28 21:28
I've created Issue #946 which covers the remaining general issue of Unicode characters in MS comments. As far as I'm aware, the problem which this issue reported has been addressed. It's that subsequent investigation highlighted another existing issue which has been present for a long time, but I don't recall having an Issue which addressed it.

**Closed by makyen** 2022-08-28 21:28 UTC
